<?php

return [
    "Allergologia",
    "Andrologia",
    "Anestesiologia",
    "Cardiologia",
    "Chirurgia Bariatrica",
    "Chirurgia Estetica",
    "Chirurgia Generale",
    "Chirurgia Generale e d'Urgenza",
    "Chirurgia Maxillo-Facciale",
    "Chirurgia Pediatrica",
    "Chirurgia Plastica e Ricostruttiva",
    "Chirurgia Toracica",
    "Dermatologia",
    "Endoscopia",
    "Endocrinologia",
    "Ematologia",
    "Fisiatria",
    "Gastroenterologia",
    "Generale",
    "Geriatria",
    "Ginecologia e Ostetricia",
    "Ginecologia Oncologica",
    "Immunologia",
    "Malattie Infettive",
    "Medicina d'Emergenza",
    "Medicina Estetica",
    "Medicina Fisica e Riabilitativa",
    "Medicina Interna",
    "Medicina Legale",
    "Medicina Nucleare",
    "Medicina del Lavoro",
    "Medicina Palliativa",
    "Medicina Preventiva",
    "Neurologia",
    "Neurologia Pediatrica",
    "Nefrologia",
    "Nutrizione Clinica",
    "Oftalmologia",
    "Oncologia",
    "Ortopedia",
    "Otorinolaringoiatria",
    "Pediatria",
    "Patologia",
    "Psichiatria",
    "Psicologia Clinica",
    "Pneumologia",
    "Radiologia",
    "Reumatologia",
    "Terapia del Dolore",
    "Tossicologia",
    "Urologia"
];
