<?php

return [
    "Anestesiologia",
    "Cardiologia",
    "Dermatologia",
    "Endocrinologia",
    "Gastroenterologia",
    "Geriatria",
    "Ginecologia e Ostetricia",
    "Immunologia",
    "Malattie Infettive",
    "Medicina Interna",
    "Medicina Nucleare",
    "Nefrologia",
    "Neurologia",
    "Oftalmologia",
    "Oncologia",
    "Ortopedia",
    "Otorinolaringoiatria",
    "Pediatria",
    "Psichiatria",
    "Radiologia",
    "Reumatologia",
    "Urologia",
    "Chirurgia Generale",
    "Chirurgia Vascolare",
    "Chirurgia Pediatrica",
    "Neurochirurgia",
    "Medicina dello Sport",
    "Patologia",
    "Medicina Legale",
    "Medicina del Lavoro",
    "Allergologia",
    "Ematologia",
    "Medicina d'Emergenza",
    "Tossicologia",
    "Endoscopia",
    "Chirurgia Plastica e Ricostruttiva",
    "Medicina Palliativa",
    "Psicologia Clinica",
    "Ginecologia Oncologica",
    "Pneumologia",
    "Chirurgia Toracica",
    "Ostetricia",
    "Andrologia",
    "Chirurgia Maxillo-Facciale",
    "Medicina Fisica e Riabilitativa",
    "Chirurgia Bariatrica",
    "Fisiatria",
    "Chirurgia Generale e d'Urgenza",
    "Neurologia Pediatrica",
    "Nutrizione Clinica",
    "Medicina Preventiva",
    "Medicina Estetica",
    "Terapia del Dolore",
    "Chirurgia Estetica"
];