<?php

return [
    [ 
        "id" => 1,
        "name" => "Giovanni",
        "email" => "giovanni@example.com",
        "content" => "Molto soddisfatto del trattamento ricevuto. Consiglio vivamente questo dottore.",
        "doctor_id" => 5,
    ],
    [ 
        "id" => 2,
        "name" => "Maria",
        "email" => "maria@example.com",
        "content" => "Il medico è stato molto professionale e ha risolto il mio problema in breve tempo.",
        "doctor_id" => 2,
    ],
    [ 
        "id" => 3,
        "name" => "Luca",
        "email" => "luca@example.com",
        "content" => "Dottore competente, ma un po' troppo tempo d'attesa per la visita.",
        "doctor_id" => 3,
    ],
    [ 
        "id" => 4,
        "name" => "Sofia",
        "email" => "sofia@example.com",
        "content" => "Esperienza positiva, sicuramente tornerò per un altro controllo.",
        "doctor_id" => 7,
    ],
    [ 
        "id" => 5,
        "name" => "Alessandro",
        "email" => "alessandro@example.com",
        "content" => "Un medico molto empatico, mi ha messo subito a mio agio. Lo consiglio.",
        "doctor_id" => 9,
    ],
    [ 
        "id" => 6,
        "name" => "Francesca",
        "email" => "francesca@example.com",
        "content" => "Purtroppo non sono rimasta soddisfatta. La diagnosi non è stata corretta.",
        "doctor_id" => 1,
    ],
    [ 
        "id" => 7,
        "name" => "Paolo",
        "email" => "paolo@example.com",
        "content" => "Ottima esperienza, il dottore ha risposto a tutte le mie domande in maniera chiara.",
        "doctor_id" => 4,
    ],
    [ 
        "id" => 8,
        "name" => "Elena",
        "email" => "elena@example.com",
        "content" => "Il dottore è stato molto gentile e competente. Lo raccomando a chiunque.",
        "doctor_id" => 10,
    ],
    [ 
        "id" => 9,
        "name" => "Giorgio",
        "email" => "giorgio@example.com",
        "content" => "Una visita veloce ma accurata. Il trattamento mi ha aiutato molto.",
        "doctor_id" => 6,
    ],
    [ 
        "id" => 10,
        "name" => "Laura",
        "email" => "laura@example.com",
        "content" => "Il medico mi ha dato una spiegazione esauriente riguardo la mia malattia. Molto soddisfatta.",
        "doctor_id" => 15,
    ],
    [ 
        "id" => 11,
        "name" => "Simone",
        "email" => "simone@example.com",
        "content" => "Un po' troppo caro per la visita, ma la qualità del servizio è alta.",
        "doctor_id" => 13,
    ],
    [ 
        "id" => 12,
        "name" => "Giulia",
        "email" => "giulia@example.com",
        "content" => "Il dottore è molto disponibile e professionale. Mi sono trovata benissimo.",
        "doctor_id" => 14,
    ],
    [ 
        "id" => 13,
        "name" => "Antonio",
        "email" => "antonio@example.com",
        "content" => "La visita è stata rapida e il trattamento è stato efficace. Grazie!",
        "doctor_id" => 8,
    ],
    [ 
        "id" => 14,
        "name" => "Chiara",
        "email" => "chiara@example.com",
        "content" => "Un'esperienza eccellente! Molto competente e attento alle esigenze del paziente.",
        "doctor_id" => 11,
    ],
    [ 
        "id" => 15,
        "name" => "Marco",
        "email" => "marco@example.com",
        "content" => "Visita molto soddisfacente. Il medico è stato molto professionale e cortese.",
        "doctor_id" => 12,
    ],
    [ 
        "id" => 16,
        "name" => "Federica",
        "email" => "federica@example.com",
        "content" => "Servizio molto rapido e ben curato. Consigliato!",
        "doctor_id" => 10,
    ],
    [ 
        "id" => 17,
        "name" => "Alberto",
        "email" => "alberto@example.com",
        "content" => "Molto professionale, tornerò sicuramente.",
        "doctor_id" => 1,
    ],
    [ 
        "id" => 18,
        "name" => "Martina",
        "email" => "martina@example.com",
        "content" => "Servizio impeccabile e visita esaustiva. Ottima esperienza.",
        "doctor_id" => 20,
    ],
    [ 
        "id" => 19,
        "name" => "Claudio",
        "email" => "claudio@example.com",
        "content" => "Efficace e veloce, consigliato!",
        "doctor_id" => 19,
    ],
    [ 
        "id" => 20,
        "name" => "Veronica",
        "email" => "veronica@example.com",
        "content" => "Mi ha aiutata molto con il mio problema.",
        "doctor_id" => 11,
    ],
    [ 
        "id" => 21,
        "name" => "Stefano",
        "email" => "stefano@example.com",
        "content" => "Il dottore è molto disponibile e professionale.",
        "doctor_id" => 5,
    ],
    [ 
        "id" => 22,
        "name" => "Valeria",
        "email" => "valeria@example.com",
        "content" => "Molto preparato e attento. Consiglio a tutti!",
        "doctor_id" => 6,
    ],
    [ 
        "id" => 23,
        "name" => "Leonardo",
        "email" => "leonardo@example.com",
        "content" => "La visita è stata completa e accurata. Lo raccomando.",
        "doctor_id" => 3,
    ],
    [ 
        "id" => 24,
        "name" => "Martina",
        "email" => "martina_smith@example.com",
        "content" => "Un'esperienza positiva. Dottore molto gentile.",
        "doctor_id" => 15,
    ],
    [ 
        "id" => 25,
        "name" => "Pietro",
        "email" => "pietro@example.com",
        "content" => "Professionale e puntuale.",
        "doctor_id" => 9,
    ],
    [ 
        "id" => 26,
        "name" => "Alice",
        "email" => "alice@example.com",
        "content" => "Il dottore è stato molto attento e chiaro nelle spiegazioni.",
        "doctor_id" => 8,
    ],
    [ 
        "id" => 27,
        "name" => "Gabriele",
        "email" => "gabriele@example.com",
        "content" => "Molto esperto e disponibile.",
        "doctor_id" => 7,
    ],
    [ 
        "id" => 28,
        "name" => "Elisabetta",
        "email" => "elisabetta@example.com",
        "content" => "Grande competenza e professionalità. Lo consiglio.",
        "doctor_id" => 10,
    ],
    [ 
        "id" => 29,
        "name" => "Fabio",
        "email" => "fabio@example.com",
        "content" => "Ottimo medico, mi ha fatto sentire a mio agio.",
        "doctor_id" => 4,
    ],
    [ 
        "id" => 30,
        "name" => "Lucia",
        "email" => "lucia@example.com",
        "content" => "Un professionista preparato e gentile.",
        "doctor_id" => 13,
    ],
    [ 
        "id" => 31,
        "name" => "Michele",
        "email" => "michele@example.com",
        "content" => "La visita è stata molto accurata e chiara.",
        "doctor_id" => 14,
    ],
    [ 
        "id" => 32,
        "name" => "Roberta",
        "email" => "roberta@example.com",
        "content" => "Ha risolto il mio problema con grande competenza.",
        "doctor_id" => 5,
    ],
    [ 
        "id" => 33,
        "name" => "Tommaso",
        "email" => "tommaso@example.com",
        "content" => "Competente e rassicurante.",
        "doctor_id" => 17,
    ],
    [ 
        "id" => 34,
        "name" => "Silvia",
        "email" => "silvia@example.com",
        "content" => "Un medico di grande umanità e professionalità.",
        "doctor_id" => 6,
    ],
    [ 
        "id" => 35,
        "name" => "Emanuele",
        "email" => "emanuele@example.com",
        "content" => "Consiglio vivamente per la sua precisione e attenzione.",
        "doctor_id" => 9,
    ],
    [ 
        "id" => 36,
        "name" => "Federico",
        "email" => "federico@example.com",
        "content" => "Molto competente e preparato.",
        "doctor_id" => 8,
    ],
    [ 
        "id" => 37,
        "name" => "Veronica",
        "email" => "veronica_jones@example.com",
        "content" => "Esperienza molto positiva. Tornerò per le prossime visite.",
        "doctor_id" => 4,
    ],
    [ 
        "id" => 38,
        "name" => "Gianni",
        "email" => "gianni@example.com",
        "content" => "Competente e cortese, un ottimo professionista.",
        "doctor_id" => 3,
    ],
    [ 
        "id" => 39,
        "name" => "Nicoletta",
        "email" => "nicoletta@example.com",
        "content" => "Molto gentile e preparato.",
        "doctor_id" => 12,
    ],
    [ 
        "id" => 40,
        "name" => "Flavio",
        "email" => "flavio@example.com",
        "content" => "Visita rapida e precisa.",
        "doctor_id" => 16,
    ],
    [ 
        "id" => 41,
        "name" => "Arianna",
        "email" => "arianna@example.com",
        "content" => "Molto preparato, mi ha risolto un problema di vecchia data.",
        "doctor_id" => 10,
    ],
    [ 
        "id" => 42,
        "name" => "Giorgia",
        "email" => "giorgia@example.com",
        "content" => "Competente e preparato. Ottimo medico.",
        "doctor_id" => 18,
    ],
    [ 
        "id" => 43,
        "name" => "Sergio",
        "email" => "sergio@example.com",
        "content" => "Mi ha fatto sentire a mio agio e ha risposto a tutte le domande.",
        "doctor_id" => 15,
    ],
    [ 
        "id" => 44,
        "name" => "Diana",
        "email" => "diana@example.com",
        "content" => "Il medico è stato chiaro e rassicurante.",
        "doctor_id" => 14,
    ],
    [ 
        "id" => 45,
        "name" => "Andrea",
        "email" => "andrea@example.com",
        "content" => "Ottimo medico, lo consiglio per competenza e disponibilità.",
        "doctor_id" => 13,
    ],
    [ 
        "id" => 46,
        "name" => "Sara",
        "email" => "sara@example.com",
        "content" => "Un dottore attento e scrupoloso.",
        "doctor_id" => 10,
    ],
    [ 
        "id" => 47,
        "name" => "Roberto",
        "email" => "roberto@example.com",
        "content" => "Ha risolto un problema che altri medici non riuscivano a trattare.",
        "doctor_id" => 11,
    ],
    [ 
        "id" => 48,
        "name" => "Franca",
        "email" => "franca@example.com",
        "content" => "Dottore competente e paziente.",
        "doctor_id" => 3,
    ],
    [ 
        "id" => 49,
        "name" => "Angelo",
        "email" => "angelo@example.com",
        "content" => "Mi sono sentito ascoltato e trattato con grande attenzione.",
        "doctor_id" => 19,
    ],
    [ 
        "id" => 50,
        "name" => "Camilla",
        "email" => "camilla@example.com",
        "content" => "Dottore molto empatico e attento.",
        "doctor_id" => 17,
    ]
]

?>
